[hyper-lin]
paru                   = true
nvidia                 = true
zsh                    = true
advanced_tools_enabled = true
niri_enabled           = true
libvirt_enabled        = true
dev_tools_enabled      = true
identity               = "~/.ssh/id_ed25519"

[hyper-lin.pacman]
multilib_enabled = true
parallel         = 4

[hyper-lin.reflector]
countries = "Ukraine,Poland,Slovakia"
sort      = "rate"
servers   = 20

[hyper-lin.ai.clients]
lmstudio    = true
claude = true

[echo-server]
paru               = true
nvidia             = true
zsh                = true
base_tools_enabled = true
libvirt_enabled    = false
dev_tools_enabled  = false
identity           = "~/.ssh/id_ed25519"

[echo-server.pacman]
multilib_enabled = true
parallel         = 2

[echo-server.reflector]
countries = "Ukraine,Poland"
sort      = "rate"
servers   = 10

[echo-server.ai.clients]
lmstudio    = false
claude = false
