[hyper-lin]
languages              = ["english", "russian", "ukrainian", "chinese"]
use_fcitx5             = true
paru_enabled           = true
nvidia_enabled         = true
zsh_enabled            = true
base_tools_enabled     = true
advanced_tools_enabled = true
niri_enabled           = true
libvirt_enabled        = true
dev_tools_enabled      = true
rbw_enabled            = true
yubikey_enabled        = true
tailscale_enabled      = true
identity               = "~/.ssh/id_ed25519"

[hyper-lin.pacman]
multilib_enabled = true
parallel         = 4

[hyper-lin.reflector]
countries = "Ukraine,Poland,Slovakia"
sort      = "rate"
servers   = 20

[hyper-lin.ai.clients]
claude_desktop = true
claude_code    = true

[echo-server]
paru_enabled           = true
nvidia_enabled         = true
zsh_enabled            = true
base_tools_enabled     = true
advanced_tools_enabled = false
niri_enabled           = false
libvirt_enabled        = true
dev_tools_enabled      = false
rbw_enabled            = false
yubikey_enabled        = false
tailscale_enabled      = true
identity               = "~/.ssh/id_ed25519"

[echo-server.pacman]
multilib_enabled = true
parallel         = 2

[echo-server.reflector]
countries = "Ukraine,Poland"
sort      = "rate"
servers   = 10

[echo-server.ai.clients]
claude_desktop = false
claude_code    = false
