monitor.alsa.rules = [
    {
        matches = [ { node.name = "~alsa_output.*" } ]
        actions = {
            update-props = {
                audio.format          = "S32LE"
                audio.rate            = 48000
                audio.channels        = 2
                audio.position        = "FL,FR"
                api.alsa.period-size  = 1024
                api.alsa.headroom     = 8192
                api.alsa.period-num   = 2
                api.alsa.disable-mmap = false
                resample.quality      = 10
                node.latency          = "1024/48000"
            }
        }
    }
]
