extends = ["laptop", "arch"]

[features.development.git]
name  = "Valentin Lukyanets"
email = "valikluks95@gmail.com"

[features.package_tools.reflector]
country = ["Ukraine", "Poland", "Slovakia", "Germany", "Hungary", "Czechia"]

[features.system.locale.console]
font     = "ter-v20n"
packages = ["terminus-font"]

[features.system.swap]
size = "20g"

[features.system.zram]
swappiness             = 100
watermark_scale_factor = 125
