extends = ["laptop", "arch"]

[features.git]
name  = "Valentin Lukyanets"
email = "valikluks95@gmail.com"

[features.reflector]
country = ["Ukraine", "Poland", "Slovakia", "Germany", "Hungary", "Czechia"]

[features.locale.console]
font     = "ter-v20n"
packages = ["terminus-font"]

[features.swap]
size = "20g"
