context.properties = {
    log.level = 0
}

context.modules = [
    { name = libpipewire-module-rt
        args = {
            nice.level   = -11
            rt.prio      = 88
            rt.time.soft = 200000
            rt.time.hard = 200000
        }
        flags = [ ifexists nofail ]
    }
    { name = libpipewire-module-protocol-native }
    { name = libpipewire-module-client-node }
    { name = libpipewire-module-adapter }
    { name = libpipewire-module-link-factory }
    { name = libpipewire-module-jack-tunnel
        args = {
            # Match your DAW's expected quantum
            jack.quantum = 1024
        }
        flags = [ ifexists nofail ]
    }
]
