# vim:set ft=sh:

MODULES=(nvidia nvidia_modeset nvidia_uvm nvidia_drm)
BINARIES=()
FILES=()
HOOKS=(base systemd autodetect microcode modconf kms keyboard keymap plymouth sd-vconsole sd-encrypt block lvm2 filesystems fsck)
#COMPRESSION_OPTIONS=()
#MODULES_DECOMPRESS="no"
