extends = ["vm"]

[git]
name = "Dotfiles Node Arch"
email = "no.email.arch@hosting.net"

[features.packaging.pacman]
contrib = true
parallel_downloads = 2

[features.packaging.makepkg]
jobs = 1
packager = "Dotfiles Node Arch <no.email.arch@hosting.net>"
options = ["!debug"]

[features.reflector]
enabled = true
country = ["Ukraine", "Poland"]
protocol = "https"
latest = 20
sort = "rate"
age = 12
completion_percent = 100
download_timeout = 10
on_calendar = "weekly"
on_boot_sec = "15min"

[features.rustup]
enabled = true
toolchain = "stable"

[features.paru]
enabled = true

[features.zsh]
enabled = true
plugins = ["git"]

[features.zsh.theme]
name = "agnoster"
